In [1]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
### Vocabulary size
voc_size=10000

## one Hot Representation

In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[9652, 8867, 2584, 1516], [9652, 8867, 2584, 4430], [9652, 9485, 2584, 3463], [1613, 2946, 5966, 9231, 8408], [1613, 2946, 5966, 9231, 6363], [2474, 9652, 3042, 2584, 3362], [6636, 2539, 3772, 9231]]


## Word Embedding Represntation

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

#### padding- making all the sentences of length A

In [8]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9652 8867 2584 1516]
 [   0    0    0    0 9652 8867 2584 4430]
 [   0    0    0    0 9652 9485 2584 3463]
 [   0    0    0 1613 2946 5966 9231 8408]
 [   0    0    0 1613 2946 5966 9231 6363]
 [   0    0    0 2474 9652 3042 2584 3362]
 [   0    0    0    0 6636 2539 3772 9231]]


In [9]:
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [12]:
print(model.predict(embedded_docs))

[[[ 2.74877064e-02  1.13176592e-02 -4.38207276e-02  4.89512421e-02
   -4.56339121e-02 -4.98057269e-02 -7.48784468e-03 -3.43904644e-03
   -1.21916905e-02  4.23696898e-02]
  [ 2.74877064e-02  1.13176592e-02 -4.38207276e-02  4.89512421e-02
   -4.56339121e-02 -4.98057269e-02 -7.48784468e-03 -3.43904644e-03
   -1.21916905e-02  4.23696898e-02]
  [ 2.74877064e-02  1.13176592e-02 -4.38207276e-02  4.89512421e-02
   -4.56339121e-02 -4.98057269e-02 -7.48784468e-03 -3.43904644e-03
   -1.21916905e-02  4.23696898e-02]
  [ 2.74877064e-02  1.13176592e-02 -4.38207276e-02  4.89512421e-02
   -4.56339121e-02 -4.98057269e-02 -7.48784468e-03 -3.43904644e-03
   -1.21916905e-02  4.23696898e-02]
  [-2.44682673e-02 -5.33864647e-03 -1.19835250e-02 -2.73883343e-02
   -1.01125725e-02  3.34492959e-02  3.00551392e-02  3.61693017e-02
   -5.63513115e-03 -2.38058809e-02]
  [-2.05230117e-02 -1.01700053e-02 -2.27205511e-02 -1.21423118e-02
    7.47014210e-03 -4.16036956e-02  2.71168686e-02 -3.16771492e-02
   -3.72805111e-

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 9652, 8867, 2584, 1516])

In [14]:
print(model.predict(embedded_docs)[0])    #(1st column) the 0 has got converted into a dimention of 10 vectors

[[ 0.02748771  0.01131766 -0.04382073  0.04895124 -0.04563391 -0.04980573
  -0.00748784 -0.00343905 -0.01219169  0.04236969]
 [ 0.02748771  0.01131766 -0.04382073  0.04895124 -0.04563391 -0.04980573
  -0.00748784 -0.00343905 -0.01219169  0.04236969]
 [ 0.02748771  0.01131766 -0.04382073  0.04895124 -0.04563391 -0.04980573
  -0.00748784 -0.00343905 -0.01219169  0.04236969]
 [ 0.02748771  0.01131766 -0.04382073  0.04895124 -0.04563391 -0.04980573
  -0.00748784 -0.00343905 -0.01219169  0.04236969]
 [-0.02446827 -0.00533865 -0.01198353 -0.02738833 -0.01011257  0.0334493
   0.03005514  0.0361693  -0.00563513 -0.02380588]
 [-0.02052301 -0.01017001 -0.02272055 -0.01214231  0.00747014 -0.0416037
   0.02711687 -0.03167715 -0.03728051  0.02128304]
 [-0.02447534 -0.03868238  0.00351263  0.00505697  0.00534846  0.04653107
  -0.03238332  0.02556926  0.02522314  0.013999  ]
 [ 0.01133054 -0.02546938 -0.03718015  0.03804244 -0.02556751  0.04728848
   0.03354224  0.03273584  0.01608622 -0.00091789]]


In [16]:
print(model.predict(embedded_docs)[5])     #(5th column) the 9652 has got converted into a dimention of 10 vectors

[[ 0.02748771  0.01131766 -0.04382073  0.04895124 -0.04563391 -0.04980573
  -0.00748784 -0.00343905 -0.01219169  0.04236969]
 [ 0.02748771  0.01131766 -0.04382073  0.04895124 -0.04563391 -0.04980573
  -0.00748784 -0.00343905 -0.01219169  0.04236969]
 [ 0.02748771  0.01131766 -0.04382073  0.04895124 -0.04563391 -0.04980573
  -0.00748784 -0.00343905 -0.01219169  0.04236969]
 [ 0.02212456 -0.00812373 -0.03417777 -0.03257265 -0.01101001 -0.04325115
  -0.04114699  0.01662493  0.03325238 -0.04784181]
 [-0.02446827 -0.00533865 -0.01198353 -0.02738833 -0.01011257  0.0334493
   0.03005514  0.0361693  -0.00563513 -0.02380588]
 [-0.00019466  0.00939821  0.01492728  0.03103603  0.02486552 -0.04160267
  -0.02535232  0.02720456  0.0072198   0.03503349]
 [-0.02447534 -0.03868238  0.00351263  0.00505697  0.00534846  0.04653107
  -0.03238332  0.02556926  0.02522314  0.013999  ]
 [-0.01870699  0.02111525  0.02679901  0.04961434  0.03695429 -0.02957015
  -0.02697315 -0.00037616  0.03808249 -0.02888652]]
